# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    left_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

    right_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 100  # Hz
    info_file_name: fixed_base
    joints:
      - joint_lift
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: arx_lift

    # Control parameters
    home_pos: [ 0.5,
                0.0, 0.594, 0.306, 0.331, 0.0, 0.0,
                0.0, 0.594, 0.306, 0.331, 0.0, 0.0 ]
    rest_pos: [ 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

left_hand_controller:
  ros__parameters:
    joint: left_gripper_joint
    force_feedback_ratio: 0.1
    force_threshold: 0.5

right_hand_controller:
  ros__parameters:
    joint: right_gripper_joint
    force_feedback_ratio: 0.1
    force_threshold: 0.5