# This config file of OpenArm Single is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    left_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

    right_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 50  # Hz
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
    
    command_interfaces:
      - position
    state_interfaces:
      - position

    future_time_offset: 2.0
    robot_name: openarm

    # Control parameters
    home_pos: [ 0.5, -0.146, 0.0, 1.281, 0.0, 0.0, -0.722,
                -0.5, 0.146, 0.0, 1.281, 0.0, 0.0, 0.722 ]
    rest_pos: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

left_hand_controller:
  ros__parameters:
    joint: left_gripper_joint
    force_feedback_ratio: 0.1
    force_threshold: 0.5

right_hand_controller:
  ros__parameters:
    joint: right_gripper_joint
    force_feedback_ratio: 0.1
    force_threshold: 0.5